baseURL ='https://1500gryz.github.io/SRH/' 
languageCode = 'en-us'
publishDir="docs"
theme = 'ananke'
title = '追寻黄河故事'
canonifyurls = true
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true